version: "3.9"
services:
  service-discovery:
    image: consul
    container_name: consul
    networks:
      - grpc_mesh
    ports:
      - 8080:8500
  request-dispatcher:
    build: 
       context: ./
       dockerfile: ./RequestDispatcher/Dockerfile
    container_name: dispatcher
    environment:
      - Discovery__Url=http://consul:8500
    depends_on:
      - service-discovery
    ports:
      - 5050:80
    networks:
      - grpc_mesh
  airtour-provider:
    build: 
        context: ./
        dockerfile: ./AirtourProvider/Dockerfile
    container_name: airtour
    environment:
      - Discovery__Url=http://consul:8500
    networks:
      - grpc_mesh
  safarbooking-provider:
    build: 
        context: ./
        dockerfile: ./SafarBookingProvider/Dockerfile
    container_name: safarbooking
    environment:
      - Discovery__Url=http://consul:8500
    networks:
      - grpc_mesh
  amadeus-provider:
    build: 
        context: ./
        dockerfile: ./AmadeusProvider/Dockerfile
    container_name: amadeus
    environment:
      - Discovery__Url=http://consul:8500
    networks:
      - grpc_mesh
  
  test-provider:
    build: 
        context: ./
        dockerfile: ./TestProvider/Dockerfile
    container_name: testprovider
    environment:
      - Discovery__Url=http://consul:8500
    networks:
      - grpc_mesh

networks:
  grpc_mesh:
    driver: bridge