version: "3.9"
services:
  service-discovery:
    image: consul
    container_name: consul
    networks:
      - grpc_mesh
  request-dispatcher:
    build: ./RequestDispatcher
    container_name: request-dispatcher
    environment:
      - Discovery__Url=http://consul:8500
    ports: 5000
    depends_on:
      - service-discovery
    networks:
      - grpc_mesh
  airtour-provider:
    build: ./AirtourProvider
    container_name: airtour-provider
    environment:
      - Discovery__Url=http://consul:8500
    ports: 5000
    depends_on:
      - service-discovery
    networks:
      - grpc_mesh
  amadeus-provider:
    build: ./AmadeusProvider
    container_name: amadeus-provider
    environment:
      - Discovery__Url=http://consul:8500
    ports: 5000
    depends_on:
      - service-discovery
    networks:
      - grpc_mesh
  test-provider:
    build: ./TestProvider
    container_name: test-provide
    environment:
      - Discovery__Url=http://consul:8500
    ports: 5000
    depends_on:
      - service-discovery
    networks:
      - grpc_mesh
  safarbooking-provider:
    build: ./SafarBookingProvider
    container_name: safarbooking-provider
    environment:
      - Discovery__Url=http://consul:8500
    ports: 5000
    depends_on:
      - service-discovery
    networks:
      - grpc_mesh
networks:
  grpc_mesh:
    driver: bridge